### PR TITLE
Modernize the tests

### LINKED ISSUE #6: Zero initialization is assumed!
The driver programs do not assign zero initial values to the variable arrays x, Fvec and Fjac. Only the nonzero initial values are programmed. As a result, if the Fortran compiler in use does not provide a switch to do zero-initialization, or the user does not use the switch, the results will most probably be completely wrong.

Correcting this deficiency should also take care of issue #5.

### LINKED ISSUE #7: Array TEMP in test_lmstr.f90, subroutine FCN, should have SAVE attribute
In Subroutine FCN of file test_lmstr.f90, the 2-D array TEMP is filled when FCN is called with IFLAG=2. When FCN is called with IFLAG=3,4,..., the argument array FJROW is filled with a row of TEMP. This will work only if TEMP is given the SAVE attribute. Please see the comments in subroutine FCN.

### LINKED ISSUE #21: Wrong intent for arguments to FCN() in example_lmder1.f90
Reported by @xecej4:

The INTENT of arguments fvec and fjac of subroutine FCN should be changed from OUT to IN OUT. As of now, when the subroutine is entered with iflag = 1, fjac becomes undefined; when entered with iflag = another value, fvec becomes undefined.

This subtle difference matters when flags such as NAG's -C=undefined or FTN95's /undef are used.

*Transferred from https://github.com/certik/minpack/issues/7*

### LINKED ISSUE #32: Modernize examples
The current tests are not actually testing anything other than running the examples. They provide no way to check the results other than by manual inspection, which makes them not reliable as regression tests.

Required steps:

- split the objective functions in separate callbacks rather than one big select case via a common block variable
- have a resource module to hold the objective functions and initializers to avoid code duplication
- actually test the outcome of the examples is correct up to a given tolerance

### LINKED ISSUE #39: Incorrect values used for n,m,ntries in test_lmder.f90
In order for the 18 problems in test_lmder.f90 to work correctly, please note that the values of n (number of fit coefficients) and m (number of "data" points to fit) should not be fixed at 40 and 65, respectively, as doing so will cause some test problems to fail to run to completion. For example, with nprob = 13, m should be 10, but calculating as if m were 65 causes overflow when the argument to exp() becomes larger than permissible, since that argument is i*x(1), and i is allowed to exceed m = 55, with x(1) = 12.998. 

Please change the outermost DO loop in the program unit as follows:

```fortran
    do 
       read *,nprob,n,m,ntries
       if (NPROb == 0) then
```

where the data are read from the file provided at Netlib: https://netlib.org/minpack/ex/file22 .

### PR DESCRIPTION
**Pull request by jacobwilliams**
work in progress..

Closes #39
Closes #32
Closes #21
Closes #7
Closes #6

### CODE REVIEW

**Comment by certik** [comment]
Thanks for working on this!

**Comment by jacobwilliams** [comment]
Can somebody fix meson for me?

**Comment by jacobwilliams** [comment]
Note: this refactor is coming along slowly but surely. I've now also got a script that pulls down and compiles the original minpack code with the original test cases. I'm going to use that as an initial cut to address #32 (i.e., just make sure we get the same answers as before...although due to bug fixes maybe some will be different).

**Comment by jacobwilliams** [comment]
## Summary

### test_hybrj

All results identical except for the following (which fail in both original and new version):

Original:
```
   2     4    134      7     4   0.1552863D-34
   2     4    139     10     4   0.7338626D-34
   2     4    149     10     4   0.4326098D-33
```
New:
```
   2     4    105      6     4   0.6046010D-34
   2     4    124      6     4   0.5013400D-34
   2     4    143     13     4   0.2112179D-33
```

**Comment by jacobwilliams** [comment]
OK, except for that one NaN issues in `test_lmstr` (which was perhaps a bug fixed by #7), the refactor now gives the same answers as before...except for that we changed the machine constants. I don't consider that a real problem (the ones we are using now are correct, whereas the old ones aren't quite).

**Comment by jacobwilliams** [comment]
Next step is adding the "truth" values to the tests so they are checked in the CI. Probably with some tolerance?

File: src/minpack.f90 [hunk 1]
```diff
@@ -97,7 +97,7 @@ subroutine fcn_lmstr(m, n, x, fvec, fjrow, iflag)
                                        !! the value of iflag should not be changed by fcn unless
                                        !! the user wants to terminate execution of lmstr.
                                        !! in this case set iflag to a negative integer.
-            real(wp), intent(in) :: x(n) !! independent variable vector
+            real(wp), intent(in) :: x(n) !! independant variable vector
```
Comment (awvwgk) [inline src/minpack.f90:100]: Typo?
```suggestion
            real(wp), intent(in) :: x(n) !! independent variable vector
```

File: .github/workflows/CI.yml [hunk 2]
```diff
@@ -66,14 +66,34 @@ jobs:
       if: ${{ matrix.build == 'fpm' }}
       run: fpm build --profile release
 
-    - name: Run test (fpm)
+    - name: Run chkder test (fpm)
```
Comment (awvwgk) [inline .github/workflows/CI.yml:69]: Can you collapse the tests again to a single step?

File: test/test_chkder.f90 [hunk 3]
```diff
@@ -1,834 +1,804 @@
...
+!*****************************************************************************************
+!>
+!  Replaced statement function in original code.
+
+    pure elemental function dfloat(i) result(f)
+        implicit none
+        integer, intent(in) :: i
+        real(wp) :: f
+        f = real(i, wp)
+    end function dfloat
```
Comment (awvwgk) [inline test/test_chkder.f90:121]: Why not replace them inline with `real(..., wp)`?

**Comment by jacobwilliams** [comment]
I think this is ready to merge. This is just an initial version of some checks. What this is doing is checking that the results are the same as the original minpack (to within some tolerance). The code does seem to be somewhat sensitive to different compilers and settings. The `lm*` ones moreso than the `hybr*` ones. There are also cases where the original minpack failed (`info>4`) and in those cases, different platforms will give much different answers, so I'm just excluding those cases from the pass/fail test.

There is more that can be done here, but I think this is a good start, just to get something in master than is checking the results. We can add to it over time.

**Review by awvwgk — COMMENTED** [review]
The `vecfcn`, `vecjac`, `initpt` functions are duplicated for each test, it would be better to define them in a single module and use them for all tests, this way further refactoring doesn't need to change test files again.

File: scripts/validate.sh [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+$COMPILER -O2 -ffixed-line-length-none ./lib/*.f ./test/file19.f -o test_lmdif_O2_$COMPILER
+$COMPILER -O2 -ffixed-line-length-none ./lib/*.f ./test/file20.f -o test_chkder_O2_$COMPILER
+
+# run tests:
+./test_hybrd_O2_$COMPILER > output_test_hybrd_O2_$COMPILER.txt
+./test_hybrj_O2_$COMPILER > output_test_hybrj_O2_$COMPILER.txt
+./test_lmder_O2_$COMPILER > output_test_lmder_O2_$COMPILER.txt
+./test_lmstr_O2_$COMPILER > output_test_lmstr_O2_$COMPILER.txt
+./test_lmdif_O2_$COMPILER > output_test_lmdif_O2_$COMPILER.txt
+./test_chkder_O2_$COMPILER > output_test_chkder_O2_$COMPILER.txt
```
Comment (certik) [inline scripts/validate.sh:111]: Given that this is Mac specific, it feels it perhaps should not be committed.

Rather, are we going to test against the original minpack? If so, then I recommend adding it to a git repository and setup proper testing, to ensure things work.

Was this used to "generate the comparisons for the unit tests"? Where are the comparisons in this PR?

File: test/test_chkder.f90 [hunk 5]
```diff
@@ -1,834 +1,804 @@
...
-         Fvec(1) = one - x(1)
-         Fvec(2) = ten*(x(2)-x(1)**2)
-      end select
-!
-!     LAST CARD OF SUBROUTINE VECFCN.
-!
-      end
+program test_chkder
+
+    use minpack_module
```
Comment (certik) [inline test/test_chkder.f90:14]: Let's use explicit imports of things that are needed? I think that is the recommended approach, as in Python.

File: scripts/validate.sh (hunk 4 above)
Comment (jacobwilliams) [reply scripts/validate.sh:111]: Yeah, I only committed this so we have a record of it. It's not part of the test suite. I used it just to output the results for the original minpack. The results ended up in the various `test_*` files. (see the `solution` subroutines).

**Comment by jacobwilliams** [comment]
> The `vecfcn`, `vecjac`, `initpt` functions are duplicated for each test, it would be better to define them in a single module and use them for all tests, this way further refactoring doesn't need to change test files again.

Yes, agree. There are other duplications (e.g., the constants). We can move them all into a separate module. I basically wanted to get it working with the "minimal" number of changes first, then we can do this type of stuff. So, we can add it to the MR or just do it later in a subsequent one.

File: test/test_chkder.f90 (hunk 3 above)
Comment (jacobwilliams) [reply test/test_chkder.f90:121]: yep, can be done. just wanted to get it working first since it was easier to do it this way.

File: .github/workflows/CI.yml (hunk 2 above)
Comment (jacobwilliams) [reply .github/workflows/CI.yml:69]: yep, can do.

File: scripts/validate.sh (hunk 4 above)
Comment (certik) [reply scripts/validate.sh:111]: I see. It seems we probably don't need to commit it then.

**Comment by certik** [comment]
Yes, we can just fix up the most obvious things that were added in this PR. If things were not ideal already in the original code, I think it's better to fix it up in subsequent PRs.

What is the logic behind `wp` (working precision)? It means double precision, correct? It won't work with single precision, right?

File: .github/workflows/CI.yml (hunk 2 above)
Comment (jacobwilliams) [reply .github/workflows/CI.yml]: ca9fb556ef686962628b23ace5b73f29cdbb9406

File: test/test_chkder.f90 (hunk 5 above)
Comment (jacobwilliams) [reply test/test_chkder.f90]: 85fb6033a73fddf836b79ac0e0fddc933bd4f2b3

**Comment by jacobwilliams** [comment]
> What is the logic behind `wp` (working precision)? It means double precision, correct? It won't work with single precision, right?

See #57

File: src/minpack.f90 (hunk 1 above)
Comment (jacobwilliams) [reply src/minpack.f90]: e145ec5012f75bd512fe2ea412032a8c2dc5c6b7

File: test/test_chkder.f90 (hunk 3 above)
Comment (jacobwilliams) [reply test/test_chkder.f90:151]: will address in #61

File: scripts/validate.sh (hunk 4 above)
Comment (jacobwilliams) [reply scripts/validate.sh:111]: Yep, I can remove it.

Comment (jacobwilliams) [reply scripts/validate.sh:111]: if we ever need it again, I put it here: https://github.com/jacobwilliams/minpack-tester

**Comment by jacobwilliams** [comment]
OK to merge? [Will address the code duplication issues in #61]

**Review by awvwgk — APPROVED** [review]
Thanks, looks good to me. Also fixes the runtime error with NAG.

**Review by certik — APPROVED** [review]
I think it's fine to merge.
